using System.Reflection;

namespace Peek.Core;

/// <summary>
/// App identity read from the entry assembly's attributes - generated by the
/// MSBuild properties in src/client/Directory.Build.props - so both the About
/// window and the main shell's version footer share one source of truth instead
/// of each hardcoding/duplicating the version string.
/// </summary>
public static class AppInfo
{
    private static readonly Assembly EntryAssembly = Assembly.GetEntryAssembly() ?? typeof(AppInfo).Assembly;

    /// <summary>
    /// May include a "+&lt;git-sha&gt;" build-provenance suffix - the .NET SDK appends
    /// one to InformationalVersion automatically when building inside a git repo, with
    /// no SourceLink package needed. Fine/expected for About; see <see cref="ShortVersion"/>
    /// for compact UI like the sidebar footer.
    /// </summary>
    public static string Version { get; } =
        EntryAssembly.GetCustomAttribute<AssemblyInformationalVersionAttribute>()?.InformationalVersion
        ?? EntryAssembly.GetName().Version?.ToString()
        ?? "0.0.0";

    /// <summary><see cref="Version"/> with any "+&lt;git-sha&gt;" build-provenance suffix stripped.</summary>
    public static string ShortVersion { get; } = Version.Split('+')[0];

    public static string Copyright { get; } =
        EntryAssembly.GetCustomAttribute<AssemblyCopyrightAttribute>()?.Copyright ?? string.Empty;
}
