<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
    <AvaloniaVersion>12.0.4</AvaloniaVersion>
    <SkiaSharpVersion>3.119.3-preview.1.1</SkiaSharpVersion>
  </PropertyGroup>
  <ItemGroup>
    <PackageVersion Include="AsyncNavigation" Version="2.0.2" />
    <PackageVersion Include="AsyncNavigation.Avalonia" Version="2.0.2" />
    <PackageVersion Include="Avalonia" Version="12.1.2" />
    <PackageVersion Include="Avalonia.Fonts.Inter" Version="12.1.2" />
    <PackageVersion Include="Avalonia.Desktop" Version="12.1.2" />
    <PackageVersion Include="Avalonia.LinuxFramebuffer" Version="$(AvaloniaVersion)" />
    <PackageVersion Include="Avalonia.iOS" Version="$(AvaloniaVersion)" />
    <PackageVersion Include="Avalonia.Browser" Version="$(AvaloniaVersion)" />
    <PackageVersion Include="Avalonia.Android" Version="$(AvaloniaVersion)" />
    <PackageVersion Include="AvaloniaUI.DiagnosticsSupport" Version="2.2.3" />
    <PackageVersion Include="DynamicData" Version="9.4.33" />
    <PackageVersion Include="Irihi.Lingua" Version="1.0.0" />
    <PackageVersion Include="LibVLCSharp" Version="3.10.1" />
    <PackageVersion Include="Microsoft.Extensions.DependencyInjection" Version="10.0.12" />
    <PackageVersion Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="10.0.12" />
    <PackageVersion Include="Microsoft.Extensions.Logging" Version="10.0.12" />
    <PackageVersion Include="Microsoft.Extensions.Logging.Abstractions" Version="10.0.12" />
    <PackageVersion Include="Microsoft.Extensions.Logging.Console" Version="10.0.12" />
    <PackageVersion Include="Microsoft.Windows.CsWin32" Version="0.3.335" />
    <PackageVersion Include="Pipboy.Avalonia" Version="1.1.5-beta-preview.17" />
    <PackageVersion Include="Pipboy.Avalonia.Fx" Version="1.1.5-beta-preview.17" />
    <PackageVersion Include="Pipboy.Avalonia.ProDataGrid" Version="1.0.2-beta-preview.17" />
    <PackageVersion Include="ProDataGrid" Version="12.1.0.4-nightly.20260917.1" />
    <PackageVersion Include="ReactiveUI" Version="24.2.0" />
    <PackageVersion Include="ReactiveUI.Primitives" Version="8.0.0" />
    <PackageVersion Include="SkiaSharp" Version="$(SkiaSharpVersion)" />
    <PackageVersion Include="SkiaSharp.NativeAssets.WebAssembly" Version="$(SkiaSharpVersion)" />
    <PackageVersion Include="System.Reactive" Version="7.0.0" />
    <PackageVersion Include="VideoLAN.LibVLC.Windows" Version="3.0.23.1" />
    <PackageVersion Include="Xamarin.AndroidX.Core.SplashScreen" Version="1.2.0.2" />
    <PackageVersion Include="ReactiveUI.Avalonia" Version="12.1.2" />
    <PackageVersion Include="ReactiveUI.SourceGenerators" Version="3.2.0" />
  </ItemGroup>
</Project>